artifact_location: file:///E:/Downloads/ConstructionSight-AI/ConstructionSight-AI/backend/app/ml/models/yolo_ppe/mlflow/413077962431014810
creation_time: 1761786339216
experiment_id: '413077962431014810'
last_update_time: 1761786339216
lifecycle_stage: active
name: E:\Downloads\ConstructionSight-AI\ConstructionSight-AI\backend\app\ml\models\yolo_ppe\runs\2025-10-30_06-05-20_PPE
