"""
Conversation memory for the Smart Query Assistant.

Fetches the last N turns of a conversation session from smart_query_history
and formats them for injection into the LLM prompt.

This enables true multi-turn context continuity:
  User: "How many PPE violations today?"
  AI:   "There were 12 violations in zone North-A..."
  User: "What about last week?"   ← resolved by conversation context
  AI:   [knows to look at ppe_incidents for last 7 days, same zone filters]

The conversation_id is a UUID generated by the frontend per chat session and
stored in smart_query_history.conversation_id.
"""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

_MAX_ANSWER_PREVIEW = 180   # characters of previous answer to include


def get_conversation_context(
    db,
    user_id: int,
    conversation_id: str | None,
    max_turns: int = 4,
) -> str:
    """
    Fetch the last max_turns Q&A pairs for this conversation and format them
    for LLM prompt injection.

    Returns '' if:
      - conversation_id is None (first message or no session tracking)
      - No prior turns found
      - DB query fails
    """
    if not conversation_id:
        return ""
    try:
        from sqlalchemy import text
        rows = db.execute(
            text("""
                SELECT question, answer, sql_used, resolved_question, query_context_json
                FROM smart_query_history
                WHERE user_id        = :uid
                  AND conversation_id = :cid
                ORDER BY created_at DESC
                LIMIT :lim
            """),
            {"uid": user_id, "cid": conversation_id, "lim": max_turns},
        ).fetchall()
    except Exception as e:
        logger.warning(f"[conversation_memory] Failed to fetch context: {e}")
        return ""

    if not rows:
        return ""

    # Reverse so oldest turn is first (chronological order)
    rows = list(reversed(rows))
    return _format(rows)


def _format(turns: list) -> str:
    """
    Format prior turns as:
    CONVERSATION HISTORY (most recent last — use for context resolution):
    [Turn 1] User: <question>
             Answer: <truncated answer>
    ...
    """
    lines = ["CONVERSATION HISTORY (most recent last — use to resolve follow-up references):"]
    for i, row in enumerate(turns, 1):
        question = (row[0] or "").strip()
        answer = (row[1] or "").strip()
        sql_used = (row[2] or "").strip() if len(row) > 2 else ""
        resolved_question = (row[3] or "").strip() if len(row) > 3 else ""
        query_context_json = (row[4] or "").strip() if len(row) > 4 else ""
        if len(answer) > _MAX_ANSWER_PREVIEW:
            answer = answer[:_MAX_ANSWER_PREVIEW].rsplit(" ", 1)[0] + "..."
        lines.append(f"[Turn {i}] User: {question}")
        if resolved_question and resolved_question != question:
            lines.append(f"         Resolved question: {resolved_question[:300]}")
        if query_context_json:
            lines.append(f"         Query context: {query_context_json[:500]}")
        elif sql_used:
            lines.append(f"         SQL used: {sql_used[:500]}")
        if answer:
            lines.append(f"         Answer: {answer}")
    return "\n".join(lines)
