artifact_uri: file:///I:/ConstructionSight AI/ConstructionSight-AI/backend/app/ml/models/yolo_ppe/mlflow/972116688398379598/cefcef7231a541eeacb9b11617f5fa1f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '972116688398379598'
lifecycle_stage: active
run_id: cefcef7231a541eeacb9b11617f5fa1f
run_name: ppe_PHASE1
run_uuid: cefcef7231a541eeacb9b11617f5fa1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1761776057231
status: 1
tags: []
user_id: Haider Ali
