artifact_location: file:///H:/ConstructionSight-AI/backend/app/ml/models/yolo_ppe/mlflow/145608455651474544
creation_time: 1774694630423
experiment_id: '145608455651474544'
last_update_time: 1774694630423
lifecycle_stage: active
name: H:\ConstructionSight-AI\backend\app\ml\models\yolo_ppe\runs\2026-03-28_15-43-38_PPE_STAGE2
