from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class SmartQueryRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=500)
    project_id: int | None = None
    force_refresh: bool = False
    mode: Literal["standard", "deep", "auto"] = "auto"
    model: str | None = None  # accepted for frontend compatibility; backend uses configured Ollama model
    conversation_id: str | None = None  # UUID generated by frontend per chat session


class EvidenceItem(BaseModel):
    label: str
    value: str


class InsightItem(BaseModel):
    text: str
    severity: Literal["success", "warning", "danger", "info"]
    icon: str


class SmartQueryResponse(BaseModel):
    answer: str
    insights: list[InsightItem]
    evidence: list[EvidenceItem]
    follow_up_suggestions: list[str]
    chart: dict[str, Any] | None
    sql_used: str | None
    duration_ms: int
    rows_returned: int
    confidence: Literal["HIGH", "MEDIUM", "LOW"]
    cached: bool
    history_id: int | None = None
    error_message: str | None = None
    mode: str = "standard"


class QueryHistoryItem(BaseModel):
    id: int
    question: str
    answer: str | None
    project_id: int | None
    mode: str
    duration_ms: int | None
    rows_returned: int | None
    cached: bool
    created_at: datetime
    conversation_id: str | None = None
    insights: list[dict[str, Any]] = Field(default_factory=list)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    chart: dict[str, Any] | None = None
    sql_used: str | None = None

    class Config:
        from_attributes = True


class ConversationSummary(BaseModel):
    conversation_id: str
    first_question: str
    last_asked: datetime
    turn_count: int
    project_id: int | None


class QuerySuggestion(BaseModel):
    category: str
    label: str
    question: str
    icon: str = "📊"


class SmartQueryStatusResponse(BaseModel):
    ollama_online: bool
    model: str
    faiss_ready: bool
    registry_tables: int = 0
