artifact_location: file:///I:/ConstructionSight AI/ConstructionSight-AI/backend/app/ml/models/yolo_ppe/mlflow/396418372278744513
creation_time: 1761771817601
experiment_id: '396418372278744513'
last_update_time: 1761771817601
lifecycle_stage: active
name: I:\ConstructionSight AI\ConstructionSight-AI\backend\app\ml\models\yolo_ppe\runs\2025-10-30_02-03-33_PPE
