artifact_location: file:///I:/ConstructionSight AI/ConstructionSight-AI/backend/app/ml/models/yolo_ppe/mlflow/972116688398379598
creation_time: 1761776057124
experiment_id: '972116688398379598'
last_update_time: 1761776057124
lifecycle_stage: active
name: I:\ConstructionSight AI\ConstructionSight-AI\backend\app\ml\models\yolo_ppe\runs\2025-10-30_03-14-10_PPE
